
export const metadata = {
  title: "React Advanced",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning>Contact page main aapka swagat hai{children}</body>
    </html>
  );
}
